language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
    allow_failures:
        - php: 7.1

before_script:
 - wget -c https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
 - composer self-update
 - composer install --prefer-source

script:
  - mkdir -p build/logs
  - composer run-script php-cs
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
